#!/bin/sh
set -e
export LC_ALL=C
export LANG=C
export LANGUAGE=C

if command -v systemctl >/dev/null 2>&1; then
  systemctl stop ab-worm.service || true
  systemctl disable ab-worm.service || true
fi
